name: Build Ant Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: temurin

    - name: Build with Ant
      run: |
        sudo apt-get install -y ant
        ant -version
        ant compile
